project_id = "ammshebfszuhmqvclfff"

[functions.generate-recipes]
verify_jwt = false

[functions.detect-ingredients]
verify_jwt = false

[functions.generate-recipe-image]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false
