/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRecipesRouteImport } from './routes/admin.recipes'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminIngredientsRouteImport } from './routes/admin.ingredients'
import { Route as AdminCommunityRouteImport } from './routes/admin.community'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminContentHomeRouteImport } from './routes/admin.content.home'
import { Route as AdminContentFeaturesRouteImport } from './routes/admin.content.features'
import { Route as AdminContentContactRouteImport } from './routes/admin.content.contact'
import { Route as AdminContentAboutRouteImport } from './routes/admin.content.about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesRoute = AdminRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIngredientsRoute = AdminIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentHomeRoute = AdminContentHomeRouteImport.update({
  id: '/content/home',
  path: '/content/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentFeaturesRoute = AdminContentFeaturesRouteImport.update({
  id: '/content/features',
  path: '/content/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentContactRoute = AdminContentContactRouteImport.update({
  id: '/content/contact',
  path: '/content/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentAboutRoute = AdminContentAboutRouteImport.update({
  id: '/content/about',
  path: '/content/about',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/ingredients': typeof AdminIngredientsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/u/$userId': typeof UUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/content/about': typeof AdminContentAboutRoute
  '/admin/content/contact': typeof AdminContentContactRoute
  '/admin/content/features': typeof AdminContentFeaturesRoute
  '/admin/content/home': typeof AdminContentHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/ingredients': typeof AdminIngredientsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/u/$userId': typeof UUserIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/content/about': typeof AdminContentAboutRoute
  '/admin/content/contact': typeof AdminContentContactRoute
  '/admin/content/features': typeof AdminContentFeaturesRoute
  '/admin/content/home': typeof AdminContentHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/ingredients': typeof AdminIngredientsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/u/$userId': typeof UUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/content/about': typeof AdminContentAboutRoute
  '/admin/content/contact': typeof AdminContentContactRoute
  '/admin/content/features': typeof AdminContentFeaturesRoute
  '/admin/content/home': typeof AdminContentHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/contact'
    | '/features'
    | '/profile'
    | '/recipes'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/community'
    | '/admin/ingredients'
    | '/admin/messages'
    | '/admin/recipes'
    | '/admin/settings'
    | '/admin/users'
    | '/u/$userId'
    | '/admin/'
    | '/admin/content/about'
    | '/admin/content/contact'
    | '/admin/content/features'
    | '/admin/content/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/community'
    | '/contact'
    | '/features'
    | '/profile'
    | '/recipes'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/community'
    | '/admin/ingredients'
    | '/admin/messages'
    | '/admin/recipes'
    | '/admin/settings'
    | '/admin/users'
    | '/u/$userId'
    | '/admin'
    | '/admin/content/about'
    | '/admin/content/contact'
    | '/admin/content/features'
    | '/admin/content/home'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/contact'
    | '/features'
    | '/profile'
    | '/recipes'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/community'
    | '/admin/ingredients'
    | '/admin/messages'
    | '/admin/recipes'
    | '/admin/settings'
    | '/admin/users'
    | '/u/$userId'
    | '/admin/'
    | '/admin/content/about'
    | '/admin/content/contact'
    | '/admin/content/features'
    | '/admin/content/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ProfileRoute: typeof ProfileRoute
  RecipesRoute: typeof RecipesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UUserIdRoute: typeof UUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes': {
      id: '/admin/recipes'
      path: '/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AdminRecipesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ingredients': {
      id: '/admin/ingredients'
      path: '/ingredients'
      fullPath: '/admin/ingredients'
      preLoaderRoute: typeof AdminIngredientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/home': {
      id: '/admin/content/home'
      path: '/content/home'
      fullPath: '/admin/content/home'
      preLoaderRoute: typeof AdminContentHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/features': {
      id: '/admin/content/features'
      path: '/content/features'
      fullPath: '/admin/content/features'
      preLoaderRoute: typeof AdminContentFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/contact': {
      id: '/admin/content/contact'
      path: '/content/contact'
      fullPath: '/admin/content/contact'
      preLoaderRoute: typeof AdminContentContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/about': {
      id: '/admin/content/about'
      path: '/content/about'
      fullPath: '/admin/content/about'
      preLoaderRoute: typeof AdminContentAboutRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminIngredientsRoute: typeof AdminIngredientsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminRecipesRoute: typeof AdminRecipesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContentAboutRoute: typeof AdminContentAboutRoute
  AdminContentContactRoute: typeof AdminContentContactRoute
  AdminContentFeaturesRoute: typeof AdminContentFeaturesRoute
  AdminContentHomeRoute: typeof AdminContentHomeRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminIngredientsRoute: AdminIngredientsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminRecipesRoute: AdminRecipesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContentAboutRoute: AdminContentAboutRoute,
  AdminContentContactRoute: AdminContentContactRoute,
  AdminContentFeaturesRoute: AdminContentFeaturesRoute,
  AdminContentHomeRoute: AdminContentHomeRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ProfileRoute: ProfileRoute,
  RecipesRoute: RecipesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UUserIdRoute: UUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
